# Generated by Django 5.2.4 on 2025-07-23 17:13

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=tinymce.models.HTMLField(),
        ),
    ]
