services:
  - type: web
    name: mi-blog
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mi_blog.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mi-blog-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
  - type: psql
    name: mi-blog-db
    ipAllowList: []
